# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    #org_name: 'HUGOxPARAMSxORG_NAME'
    #description: 'HUGOxPARAMSxDESCRIPTION'
    twitter: ''
  analytics:
    #google_tag_manager: 'HUGOxPARAMSxMARKETINGxGOOGLE_TAG_MANAGER'

# Contact (edit or remove options as required)

#email: HUGOxPARAMSxEMAIL
#phone: 'HUGOxPARAMSxPHONE'
address:
  street: ''
  city: London
  region: UK
  postcode: ''
  country: 'United Kingdom'
  country_code: GB
coordinates:
  latitude: '51.5055'
  longitude: '-0.07535'
directions: ''
office_hours: []
appointment_url: ''
contact_links: []

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-gb

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  diagram:
    enable: false
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/josephKav/josephkav.io'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
    wowchemy:
      min_length: 1
      threshold: 0.3
  map:
    provider: ''
    api_key: ''
    zoom: 15
  reading_time: false

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
